displayName=Drop Tracker
author=Unknownchuck
description= A plugin to track all your drops, summarize the data and share with friends!
tags=drops
version=0.0.1
plugins=com.droptracker.DropTrackerPLugin
build=standard